# Generated by Django 6.0.6 on 2026-08-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField()),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('wave', models.IntegerField()),
                ('image', models.CharField()),
            ],
        ),
    ]
