# Generated by Django 6.0.6 on 2026-08-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectors',
            name='number',
        ),
    ]
