# Generated by Django 6.0.6 on 2026-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('slug', models.SlugField()),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Превю_сектора',
                'verbose_name_plural': 'Превю_для_секторів',
            },
        ),
    ]
