# Generated by Django 6.0.6 on 2026-08-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('slug', models.SlugField()),
                ('description', models.CharField()),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Інформація_про_сектор',
                'verbose_name_plural': 'Інформація_про_сектори',
            },
        ),
    ]
