# Generated by Django 6.0.6 on 2026-08-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_modelinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelinfo',
            options={'verbose_name': 'Інформація_про_сектор', 'verbose_name_plural': 'Ін'},
        ),
        migrations.RemoveField(
            model_name='modelsector',
            name='slug',
        ),
    ]
