# Generated by Django 6.0.6 on 2026-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_modelinfo_options_remove_modelsector_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelSector',
        ),
        migrations.AlterModelOptions(
            name='modelinfo',
            options={'verbose_name': 'Інформація_про_сектор', 'verbose_name_plural': 'Інформація_про_сектори'},
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='img',
            field=models.ImageField(upload_to='sectors/'),
        ),
    ]
